##What are tensors?
Basically like matrices, ndarrays. Special thing is that they allow for automatic differentiation and make use of hardware acceleration.

In [1]:
import torch

In [20]:
x = torch.arange(12)
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [21]:
x.shape

torch.Size([3, 4])

In [22]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [23]:
torch.randn(3, 4)

tensor([[ 0.0463,  0.1444,  0.4609,  0.3282],
        [-0.8041,  0.6747, -0.4992,  1.5581],
        [-0.1593, -0.7802,  0.3168,  1.3506]])

In [24]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [32]:
x[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [33]:
x[1,2] = 12

In [36]:
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5, 12,  7],
        [ 8,  9, 10, 11]])

In [38]:
x[:2,:] = 12
x

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [47]:
x = torch.arange(12)
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [48]:
torch.exp(x) #basically does e^x

tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01],
        [5.4598e+01, 1.4841e+02, 4.0343e+02, 1.0966e+03],
        [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]])

In [49]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [54]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x, y), dim=1) #cat dim0 concats it upar niche. dim1 cats it side by side

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [56]:
x,y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [57]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [58]:
x.sum()

tensor(66.)

Broadcasting works according to the following two-step procedure:
* expand one or both arrays by copying elements along axes with length 1 so that after this transformation, the two tensors have the same shape;
* perform an elementwise operation on the resulting arrays.

In [59]:
#broadcasting
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [61]:
#if i do a+b then it copies over a ke columns twice and adds b to each row
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [63]:
before = id(y)
y = y + x
id(y) == before # y = y+x ke baad it allocated a new memory for y; not helpful for us we need to save memory

False

In [67]:
z = torch.zeros(12).reshape(3,4)
print(id(z),z)
z[:] = x + y
print(id(z),z)

132340573892592 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
132340573892592 tensor([[ 2.,  4., 10., 12.],
        [13., 17., 21., 25.],
        [28., 30., 32., 34.]])


In [69]:
before = id(x)
x += y
id(x) == before

True